import { FighterInfo } from './types';

export const EVENT_CONFIG = {
  INSTITUTION_NAME: 'AISSMS College of Engineering, Pune',
  INSTITUTION_AFFILIATION: 'An Autonomous Institute Affiliated with Savitribai Phule Pune University',
  INSTITUTION_ACCREDITATION: 'Accredited by NAAC with "A+" Grade | NBA - 7 UG Programmes',
  DEPARTMENT: 'Department of Artificial Intelligence and Machine Learning (AIML)',
  FESTIVAL_NAME: '21st Engineering Today-2026',
  EVENT_NAME: 'Console Conquest',
  GAME_NAME: 'Mortal Kombat 11',
  SUBTITLE: 'MORTAL KOMBAT 11 • 1V1 TOURNAMENT',
  FORMAT: '1v1 Single Elimination Knockout (4 Pools of 32 → Final 4)',
  PLATFORM: 'PlayStation 5 (Local 1v1 Versus Mode)',
  DEFAULT_MAX_SLOTS: 128,
  POOLS_COUNT: 4,
  POOL_SIZE: 32,
  EVENT_DATE_DISPLAY: '29th & 30th September 2026, 9:00 am onwards',
  EVENT_DATE: '2026-09-29T09:00:00+05:30',
  VENUE: 'Room No. 340, AISSMS COE Campus',
  TAGLINE: 'Choose your fighter. Enter the arena. Defeat your opponent.',
  ENTRY_FEE: '₹100 per participant',
  ENTRY_TYPE: 'Individual (1 Player, 1v1)',
  ROUND_TIME: '90 seconds per round (Standard PS5 offline timer)',
  PRIZE_POOL_TOTAL: '₹8,000/-',
  FIRST_PRIZE: '₹5,000/- (Tournament Champion)',
  SECOND_PRIZE: '₹3,000/- (Runner-up)',
  THIRD_PRIZE: '3rd-Place Match Winner (Bronze Podium)',
  PARTICIPATION_CERTIFICATE: 'Official Participation Certificate to all participants',
  COORDINATORS: {
    facultyCoordinator: 'Mrs. Rupali S. Saha (Dept. ET Coordinator)',
    hodAIML: 'Dr. D. M. Ujalambkar (H.O.D. AIML)',
    jointGeneralSecretary: 'Mr. Parth S. Suryawanshi (+91 9529425106)',
    eventCoordinator: 'Lokesh Joshi (+91 7558610917)',
    coCoordinator: 'Pratosh Jadhar (+91 9112157569)',
  },
};

export const OFFICIAL_RULES = [
  {
    id: 1,
    title: 'Prescribed Entry Format',
    details: 'Participants must register according to the prescribed entry format with valid student credentials.',
  },
  {
    id: 2,
    title: 'Zero Automatic Byes',
    details: 'Every registered player must compete from Round 1; automatic byes are strictly not permitted.',
  },
  {
    id: 3,
    title: 'Group Stage Series Length',
    details: 'Group matches in Round of 32 (R32), Round of 16 (R16), Quarterfinals (QF), and Semifinals (SF) are Best of 1 Game.',
  },
  {
    id: 4,
    title: 'Finals Series Length',
    details: 'Group Finals and Championship Semifinals / 3rd-Place matches are Best of 3 Games (First to 2 wins). The Grand Final is Best of 5 Games (First to 3 wins).',
  },
  {
    id: 5,
    title: 'Official Controller & Settings Policy',
    details: 'Participants must use only default/organizer PlayStation 5 controllers and must not alter console settings without referee consent.',
  },
  {
    id: 6,
    title: 'Arena Zone Confinement',
    details: 'Participants must remain within the tournament arena zone (Room No. 340) until their group bracket concludes.',
  },
  {
    id: 7,
    title: 'Reporting Desk Call',
    details: 'Players must report to their assigned station desk 5 minutes prior to scheduled match call time.',
  },
  {
    id: 8,
    title: 'Strict 2-Minute Grace Period & Forfeit',
    details: 'A strict 2-minute grace period is enforced. Non-reporting players forfeit the match via walkover. Opponents must be present at the station.',
  },
  {
    id: 9,
    title: 'Anti-Cheat & Hardware Integrity',
    details: 'Zero tolerance for cheating, hardware manipulation, button macros, or exploiting engine glitches.',
  },
  {
    id: 10,
    title: 'Zero Tolerance Code of Conduct',
    details: 'Verbal abuse, intimidation, physical aggression, or equipment mistreatment will result in immediate disqualification and removal from the venue.',
  },
  {
    id: 11,
    title: 'Technical Anomalies & Final Authority',
    details: 'Technical anomalies must be signaled immediately to the floor marshal. The Tournament Director / Volunteer decision will be the final and binding decision.',
  },
  {
    id: 12,
    title: 'Sportsmanship & Fair Play',
    details: 'Participants are expected to maintain fair play and respect for opponents, volunteers, organizers, and campus equipment.',
  },
];

export const MATCH_FORMAT_SETTINGS = {
  stageProgression: [
    { stage: 'Registration', players: '128 Total Contenders', format: 'Randomized public draw into 4 pools of 32', advancement: 'All 128 compete from Round 1' },
    { stage: 'Group A', players: '32 Contenders', format: 'R32 (16) → R16 (8) → QF (4) → SF (2) → Group Final (1)', advancement: '1 Pool Champion advances to Finals' },
    { stage: 'Group B', players: '32 Contenders', format: 'R32 (16) → R16 (8) → QF (4) → SF (2) → Group Final (1)', advancement: '1 Pool Champion advances to Finals' },
    { stage: 'Group C', players: '32 Contenders', format: 'R32 (16) → R16 (8) → QF (4) → SF (2) → Group Final (1)', advancement: '1 Pool Champion advances to Finals' },
    { stage: 'Group D', players: '32 Contenders', format: 'R32 (16) → R16 (8) → QF (4) → SF (2) → Group Final (1)', advancement: '1 Pool Champion advances to Finals' },
    { stage: 'Championship Stage', players: '4 Pool Champions', format: 'Semifinal 1 (A vs B, Bo3) • Semifinal 2 (C vs D, Bo3) • Grand Final (Bo5) • 3rd-Place Match (Bo3)', advancement: '1st, 2nd, and 3rd Podium Decided' },
  ],
  consoleSettings: [
    { label: 'Platform & Setup', value: 'PlayStation 5 • Local 1v1 Versus Mode' },
    { label: 'Match Timer', value: 'Standard 90 seconds round timer' },
    { label: 'Arena Selection', value: 'Random arena selection for Game 1' },
    { label: 'Characters & Controls', value: 'Any official roster fighter. Default/organizer controllers only. No setting alterations without referee consent.' },
  ],
};

export const MK11_ROSTER: FighterInfo[] = [
  {
    name: 'Scorpion',
    title: 'Shirai Ryu Grandmaster',
    archetype: 'Hellfire Rushdown',
    color: '#eab308',
    iconLetter: 'SC',
    signatureMove: 'Spear & Hell Port',
    description: 'Resurrected ninja with lethal chain spear strikes and hellfire teleports.',
  },
  {
    name: 'Sub-Zero',
    title: 'Grandmaster of the Lin Kuei',
    archetype: 'Cryomancer / Mix-up',
    color: '#0284c7',
    iconLetter: 'SZ',
    signatureMove: 'Ice Ball & Slide',
    description: 'Master of cryomancy capable of freezing opponents mid-strike and slide mix-ups.',
  },
  {
    name: 'Raiden',
    title: 'God of Thunder',
    archetype: 'Zoner / High Voltage',
    color: '#38bdf8',
    iconLetter: 'RD',
    signatureMove: 'Lightning Bolt & Torpedo',
    description: 'Immortal protector of Earthrealm commanding storm electricity and aerial flight.',
  },
  {
    name: 'Liu Kang',
    title: 'Champion of Earthrealm',
    archetype: 'Speed Pressure / Martial Artist',
    color: '#ef4444',
    iconLetter: 'LK',
    signatureMove: 'Bicycle Kick & Flying Dragon',
    description: 'Legendary Shaolin monk wielding blistering kicks and dragon fire.',
  },
  {
    name: 'Noob Saibot',
    title: 'Shadow of the Netherrealm',
    archetype: 'Shadow Clone / Space Control',
    color: '#a855f7',
    iconLetter: 'NS',
    signatureMove: 'Shadow Slide & Tele-Slam',
    description: 'Wraith utilizing shadowy apparitions to strike simultaneously from multiple angles.',
  },
  {
    name: 'Shang Tsung',
    title: 'Soul Stealer',
    archetype: 'Shape-shifter / Zoner',
    color: '#10b981',
    iconLetter: 'ST',
    signatureMove: 'Soul Steal & Fire Skull',
    description: 'Deceptive sorcerer capable of stealing opponent powers and morphing forms.',
  },
  {
    name: 'Johnny Cage',
    title: 'Hollywood Star',
    archetype: 'Frame Trap / Strikethrough',
    color: '#f59e0b',
    iconLetter: 'JC',
    signatureMove: 'Shadow Kick & Nut Punch',
    description: 'Action superstar armed with devastating green shadow energy and swagger.',
  },
  {
    name: 'Sonya Blade',
    title: 'Special Forces General',
    archetype: 'High-Low Pressure / Mix-up',
    color: '#06b6d4',
    iconLetter: 'SB',
    signatureMove: 'Energy Rings & Air Control',
    description: 'Decorated commander equipped with high-tech ordnance and martial discipline.',
  },
  {
    name: 'Baraka',
    title: 'Tarkatan Warlord',
    archetype: 'Brawler / Heavy Bleed',
    color: '#dc2626',
    iconLetter: 'BK',
    signatureMove: 'Blade Spark & Chop Chop',
    description: 'Ferocious warrior with retractable arm blades and relentless melee frenzy.',
  },
  {
    name: 'Fujin',
    title: 'God of Wind',
    archetype: 'Aerial Mobility / Whirler',
    color: '#14b8a6',
    iconLetter: 'FJ',
    signatureMove: 'Tornado & Wind Kicks',
    description: 'Graceful wind deity slicing through air with crossbow and levitation combos.',
  },
];
